"""Pure, point-in-time-aware quantitative research primitives.

This package intentionally contains no connectors, persistence, scheduler, or
presentation code. Public functions consume caller-supplied data and return
typed results or pandas objects with documented numerical conventions.
"""

from quant_raas.quant.anomalies import (
    AbnormalReturnResult,
    anomaly_flags,
    fit_abnormal_return_model,
    rolling_zscore,
    volume_zscore,
)
from quant_raas.quant.earnings import EarningsAnalysis, earnings_event_features, surprise_ratio
from quant_raas.quant.estimates import (
    EstimateDispersion,
    estimate_dispersion,
    estimate_revisions,
    latest_estimates_as_of,
    revision_breadth,
)
from quant_raas.quant.event_study import (
    EventStudyResult,
    EventStudySpec,
    EventWindow,
    SessionAlignment,
    align_event_to_session,
    extract_event_windows,
    standard_event_spec,
    summarize_event_windows,
)
from quant_raas.quant.factors import (
    NormalizedFactor,
    cross_sectional_zscore,
    momentum_12_1,
    normalize_factor,
    residual_momentum,
    rolling_beta,
    rolling_factor_exposures,
    short_term_reversal,
    winsorize_cross_section,
)
from quant_raas.quant.macro import (
    latest_macro_vintages_as_of,
    macro_event_study,
    macro_surprise,
    rolling_macro_sensitivities,
    rolling_standardized_surprise,
    standardized_macro_changes,
)
from quant_raas.quant.options import (
    DeltaRiskReversal,
    PutCallMetrics,
    delta_risk_reversal,
    implied_realized_spread,
    put_call_ratios,
    select_target_expiry,
)
from quant_raas.quant.ownership import (
    InsiderActivity,
    InstitutionalChange,
    ShortInterestMetrics,
    insider_activity,
    institutional_position_change,
    latest_ownership_snapshots_as_of,
    short_interest_metrics,
)
from quant_raas.quant.returns import (
    ReturnSummary,
    annualized_arithmetic_return,
    annualized_volatility,
    compound_returns,
    horizon_returns,
    intraday_return,
    log_returns,
    overnight_gap,
    realized_cagr,
    relative_return,
    relative_strength_index,
    rolling_total_return,
    sharpe_ratio,
    simple_returns,
    summarize_returns,
)
from quant_raas.quant.risk import (
    BetaEstimate,
    RiskSummary,
    beta_estimate,
    downside_deviation,
    historical_expected_shortfall,
    historical_value_at_risk,
    maximum_drawdown,
    rolling_volatility,
    summarize_risk,
)
from quant_raas.quant.seasonality import (
    SeasonalityResult,
    compound_period_returns,
    monthly_seasonality,
    weekday_seasonality,
)
from quant_raas.quant.statistics import (
    BootstrapResult,
    DescriptiveStatistics,
    FDRResult,
    StatisticalTestResult,
    benjamini_hochberg,
    block_bootstrap_mean,
    descriptive_statistics,
    mean_test_hac,
    mean_test_iid,
)
from quant_raas.quant.valuation import (
    ValuationDecomposition,
    ValuationDistribution,
    historical_valuation_distribution,
    peer_relative_zscore,
    valuation_decomposition,
)

# Public result types are grouped before functions to make API discovery easier.
__all__ = [
    "AbnormalReturnResult",
    "BetaEstimate",
    "BootstrapResult",
    "DeltaRiskReversal",
    "DescriptiveStatistics",
    "EarningsAnalysis",
    "EstimateDispersion",
    "EventStudyResult",
    "EventStudySpec",
    "EventWindow",
    "FDRResult",
    "InsiderActivity",
    "InstitutionalChange",
    "NormalizedFactor",
    "PutCallMetrics",
    "ReturnSummary",
    "RiskSummary",
    "SeasonalityResult",
    "SessionAlignment",
    "ShortInterestMetrics",
    "StatisticalTestResult",
    "ValuationDecomposition",
    "ValuationDistribution",
    "align_event_to_session",
    "annualized_arithmetic_return",
    "annualized_volatility",
    "anomaly_flags",
    "benjamini_hochberg",
    "beta_estimate",
    "block_bootstrap_mean",
    "compound_period_returns",
    "compound_returns",
    "cross_sectional_zscore",
    "delta_risk_reversal",
    "descriptive_statistics",
    "downside_deviation",
    "earnings_event_features",
    "estimate_dispersion",
    "estimate_revisions",
    "extract_event_windows",
    "fit_abnormal_return_model",
    "historical_expected_shortfall",
    "historical_valuation_distribution",
    "historical_value_at_risk",
    "horizon_returns",
    "implied_realized_spread",
    "insider_activity",
    "institutional_position_change",
    "intraday_return",
    "latest_estimates_as_of",
    "latest_macro_vintages_as_of",
    "latest_ownership_snapshots_as_of",
    "log_returns",
    "macro_event_study",
    "macro_surprise",
    "maximum_drawdown",
    "mean_test_hac",
    "mean_test_iid",
    "momentum_12_1",
    "monthly_seasonality",
    "normalize_factor",
    "overnight_gap",
    "peer_relative_zscore",
    "put_call_ratios",
    "realized_cagr",
    "relative_return",
    "relative_strength_index",
    "residual_momentum",
    "revision_breadth",
    "rolling_beta",
    "rolling_factor_exposures",
    "rolling_macro_sensitivities",
    "rolling_standardized_surprise",
    "rolling_total_return",
    "rolling_volatility",
    "rolling_zscore",
    "select_target_expiry",
    "sharpe_ratio",
    "short_interest_metrics",
    "short_term_reversal",
    "simple_returns",
    "standard_event_spec",
    "standardized_macro_changes",
    "summarize_event_windows",
    "summarize_returns",
    "summarize_risk",
    "surprise_ratio",
    "valuation_decomposition",
    "volume_zscore",
    "weekday_seasonality",
    "winsorize_cross_section",
]
